# -*- coding: utf-8 -*-
# EBITS TechCon Module. See LICENSE file for full copyright and licensing details.

{
    'name': 'Customized Sales Module',
    'version': '1.0',
    'category': 'Sales',
    'sequence': 100,
    'summary': 'Customized Sale Module',
    'description': """ """,
    'author': 'EBITS TechCon',
    'website': 'http://www.ebitstechcon.com',
    'depends': ['base', 'sale', 'account', 'stock', 'product', 'sale_stock', 'sale_mrp', 'sales_team', 
        'ebits_custom_base', 'warehouse_stock_restrictions', 'sale_management'],
    'data': [
        "security/sale_security.xml",
        "security/ir.model.access.csv",
        #"wizard/sale_make_invoice_advance_views.xml",
        "wizard/sale_order_action_wizard_view.xml",
        "wizard/sale_quotation_split_view.xml",
        "wizard/sale_register_report_view.xml",
        # "wizard/sale_register_detailed_report_view.xml",
        "wizard/status_wise_sales_orders_report_view.xml",
        # "wizard/sales_target_report_view.xml",
        "wizard/sales_orders_detailed_report_view.xml",
        "wizard/sale_register_summary_report_view.xml",
        "views/stock_view.xml",
        # "views/sale_org_view.xml",
        "views/sale_amendment_view.xml",
        "views/sale_view.xml",
        "report/sale_order_cash_report.xml",
        "report/sale_order_report.xml",
        # "views/account_invoice.xml",
        #"views/sale_target_view.xml",
        "report/sale_report_custom_templates.xml",
        "report/sale_report.xml",
        # "report/invoice_account_test.xml",
        # "report/vendor_account_report.xml",

        ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}
