# -*- coding: utf-8 -*-
# EBITS TechCon Module

{
    'name': 'ebits_custom_stock',
    'version': '17.0',
    'category': 'Sales',
    'sequence': 100,
    'summary': 'Customized Stock Module',
    'description': """ """,
    'author': 'EBITS TechCon',
    'website': 'http://www.ebitstechcon.com',
    'license': 'LGPL-3',
    
    'depends': ['base','ebits_custom_base','product', 'sale' , 'sales_team', 'purchase', 'account', 'stock', 'sale_stock', 'stock_account','stock_landed_costs','mrp','warehouse_stock_restrictions', "ebits_custom_purchase", "ebits_custom_mrp"],
    
    # 'depends': ['base', 'product', 'sale' , 'sales_team', 'purchase', 'account', 'stock', 'sale_stock', 'stock_account', 'stock_landed_costs', 'mrp', 'procurement', 'ebits_custom_base', 'ebits_custom_account', 'report'],
    
    'data': [
        "security/stock_security.xml",
        "security/ir.model.access.csv",
        "wizard/branch_rol_report_wizard_view.xml",
        "wizard/inentory_report_view.xml",
        "wizard/inventory_valuation_report_view.xml",
        "wizard/stock_backorder_confirmation_views.xml",
        "wizard/rol_report_wizard_view.xml",
        "wizard/details_wizard.xml",
        "wizard/product_incoming_report_view.xml",
        "wizard/sale_return_report_wizard_view.xml",
        "wizard/purchase_return_report_wizard_view.xml",
        "wizard/stock_return_picking_view.xml",
        "wizard/stock_register.xml",
        "wizard/stock_change_product_qty_views.xml",
        "wizard/stock_register_summary.xml",
        "views/stock_branch_orderpoint_views.xml",
        "views/stock_view.xml",
        "views/stock_actions_view.xml",
        "views/product_view.xml",
        "views/stock_landed_cost_view.xml",
        "views/report_inventory_valuation_pdf_view.xml",
        "views/procurement_view.xml",
        "views/internal_location_transfer_view.xml",
        "views/product_extend_view.xml",
        "report/internal_stock_transfer_issue.xml",
        "report/stock_picking_goods_transfer_rml_report.xml",
        "report/delivery_order_report.xml",
        "report/sale_return_note_temp.xml",
        "report/purchase_return_note.xml",
        "report/packing_slip_report.xml",
        "report/goods_receipt_note.xml",
        "report/inventory_valuation_date_report.xml",
        "report/inventory_valuation_report.xml",
        "report/rol_report_view.xml",
        "report/branch_rol_report_view.xml",
        # "data/stock_data.xml",
        ],
    'post_init_hook': '_post_init_code_constraint',
    'installable': True,
    'auto_install': False,
    'application': True,
}
