# -*- coding: utf-8 -*-
# Part of EBITS TechCon

{
    'name': "Customized Account Module",
    'version': "1.0",
    'category': "Account",
    'sequence': 100,
    'summary': "Customized Account Module",
    'description': """ """,
    'author': "EBITS TechCon",
    'website': "http://www.ebitstechcon.com",
    'depends': ['base', 'sale', 'purchase','stock', 'product', 'sale_stock', 'sales_team',
                'account', 'account_budget', 'account_asset', 'ebits_custom_base','account_accountant'
                ],

    #report_xlsx,account_cancel

    'data': [
        "data/ir_sequence_data.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
#         "wizard/account_chart_view.xml",
#         "wizard/analytic_account_chart_view.xml",
        "wizard/account_payment_action_wizard_view.xml",
        "wizard/account_move_cancel_action_wizard_view.xml",
#         "wizard/account_budget_report_wizard_view.xml",
#         "wizard/account_report_partner_ledger_view.xml",
#         "wizard/account_report_general_ledger_view.xml",
#         "wizard/account_report_aged_partner_balance_view.xml",
#         "wizard/account_report_trial_balance_view.xml",
#         "wizard/account_financial_report_view.xml",
#         "wizard/aged_partner_balance_wizard_view.xml",
#         "wizard/account_invoice_refund_view.xml",
#         "wizard/bank_charges_action_wizard_view.xml",
#         "wizard/invoice_outstanding_report_view.xml",
#         "wizard/supplier_invoice_outstanding_report_view.xml",
#         "wizard/payment_collection_report_view.xml",
#         "wizard/customer_sale_invoice_report_view.xml",
#         "wizard/vat_report_sale_wizard_view.xml",
#         "wizard/vat_report_purchase_wizard_view.xml",
#         "wizard/sale_invoice_datailed_report_wizard_view.xml",
#         "wizard/purchase_invoice_detailed_report_wizard_view.xml",
#         "wizard/account_entries_report_wizard_view.xml",
#         "wizard/analytic_entries_report_wizard_view.xml",
#         "wizard/lc_report_wizard_view.xml",
        "wizard/invoice_cancel_reason_wizard_view.xml",
#         "wizard/brs_report_wizard_view.xml",
#         "wizard/purchase_invoice_register_report_wizard_view.xml",
# #        "wizard/sales_mis_report_view.xml",
#         "wizard/mis_report_view.xml",
#         "wizard/purchase_invoice_register_summary_report_view.xml",
#         "wizard/account_update_lock_date.xml",
        "views/account.xml",
        # "views/account_journal_dashboard_view.xml",
        "views/account_invoice_org_view.xml",
        "views/account_invoice_view.xml",
        "views/account_payment_view.xml",
        "views/account_analytic_account.xml",
        # "views/account_move_forex_view.xml",
        "views/account_budget_extend_view.xml",
        "views/npg_bank_account_reconciliation_view.xml",
        # "views/report_overdue.xml",
        "views/res_config_view.xml",

        # "report/report_agedpartnerbalance_currency.xml",
        # "report/layouts.xml",
        # "report/report_invoice.xml",
        # "report/report_partnerledger.xml",
        # "report/report_generalledger.xml",
        # "report/report_trialbalance.xml",
        # "report/report_financial.xml",
        # "report/report_partnerledger_currency.xml",
        # "report/report_agedpartnerbalance.xml",
        # "report/aged_partner_balance.xml",
        # "report/aged_partner_balance_other_currency.xml",
        # "report/open_items.xml",
        # "report/account_invoice_report_view.xml",
        # "report/report_financial_custom_hierarchy.xml",
        "views/account_invoice_report_view.xml",
        ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
